import { useState } from 'react';
import { useRegisterDevice, useAvailableDeviceIds } from '../../lib/hooks/useProjectDevices';

interface RegisterDeviceModalProps {
  projectId: string;
  isOpen: boolean;
  onClose: () => void;
}

export function RegisterDeviceModal({ projectId, isOpen, onClose }: RegisterDeviceModalProps) {
  const [deviceName, setDeviceName] = useState('');
  const [deviceNumber, setDeviceNumber] = useState<number>(1);
  const { data: availableIds } = useAvailableDeviceIds(projectId);
  const { mutate: registerDevice, isPending } = useRegisterDevice();

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    registerDevice(
      { name: deviceName, projectId, deviceNumber },
      {
        onSuccess: (data: { composite_device_id: string; id: string; registered_at: string }) => {
          console.log(`Device ${data.composite_device_id} registered!`);
          // Device key is auto-generated by ESP and registered on first heartbeat
          alert(`Device ${data.composite_device_id} registered successfully!\n\nConfigure your ESP with this Device ID: ${data.composite_device_id}\n\nThe device will auto-generate its security key.`);
          setDeviceName('');
          onClose();
        },
        onError: (error: Error) => {
          console.error('Failed to register device:', error.message);
          alert(error.message);
        },
      }
    );
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-white rounded-lg p-6 max-w-md w-full mx-4">
        <h2 className="text-2xl font-bold mb-4">Register New Device</h2>
        <form onSubmit={handleSubmit}>
          <div className="mb-4">
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Device Name *
            </label>
            <input
              type="text"
              value={deviceName}
              onChange={(e) => setDeviceName(e.target.value)}
              className="w-full px-3 py-2 border border-gray-300 rounded-md"
              required
              maxLength={100}
              placeholder="e.g., Temperature Sensor"
            />
          </div>

          <div className="mb-4">
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Device ID *
            </label>
            <select
              value={deviceNumber}
              onChange={(e) => setDeviceNumber(Number(e.target.value))}
              className="w-full px-3 py-2 border border-gray-300 rounded-md"
              required
            >
              {availableIds?.map((id) => (
                <option key={id.device_number} value={id.device_number}>
                  {id.device_id}
                </option>
              ))}
            </select>
            {availableIds && availableIds.length === 0 && (
              <p className="text-red-600 text-sm mt-1">
                No available device IDs. Delete a device to free up an ID.
              </p>
            )}
          </div>

          <div className="flex justify-end gap-2">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 text-gray-700 hover:bg-gray-100 rounded-md"
              disabled={isPending}
            >
              Cancel
            </button>
            <button
              type="submit"
              className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:opacity-50"
              disabled={isPending || !availableIds || availableIds.length === 0}
            >
              {isPending ? 'Registering...' : 'Register Device'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
